### ISSUE TITLE
7월 4주차(07/22 ~ 07/26) To do

### ISSUE THREAD

**Issue by bin-e** [bin-e/TIL#27]
# TO-DO
- [x] 맥북에 도커 제대로 셋팅
- [ ] 도커 기반 Python Django & Database 셋팅
- [ ] 기본 API 골조 만들기
- [ ] Django 사용 웹 인증 구현
- [x] API 문서화 플랫폼 Swagger 사용해보기
